title:            Okey Chima
description:      Okey's Sandbox
url:              http://maziokey.github.io
signoff:          Okey Chima
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://maziokey.github.io
    external:     true
  - name:         Email
    url:          mailto:okeyluvsu2004@yahoo.com
    external:     true
  - name:         GitHub
    url:          http://github.com/maziokey
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
